<Project>
	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<RepositoryType>git</RepositoryType>
		<DebugType>portable</DebugType>
		<Deterministic>true</Deterministic>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
		<RepositoryUrl>https://github.com/Analogy-LogViewer/Analogy.Interfaces</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Analogy-LogViewer/Analogy.Interfaces</PackageProjectUrl>
	</PropertyGroup>
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.StartsWith('Debug'))">
		<DefineConstants>$(DefineContants);DEBUG</DefineConstants>
		<Optimize>false</Optimize>
	</PropertyGroup>
	<PropertyGroup Condition="$(Configuration.StartsWith('Release'))">
		<Optimize>true</Optimize>
	</PropertyGroup>
	<ItemGroup>
		<AdditionalFiles Include="$(MSBuildThisFileDirectory)/BannedSymbols.txt" Link="Properties/BannedSymbols.txt" />
	</ItemGroup>
</Project>
